services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    hostname: localhost
    volumes:
    - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
    - ./.docker/mongodb/data/db/:/data/db/
    - ./.docker/mongodb/data/log/:/var/log/mongodb/
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: root 
      MONGO_INITDB_DATABASE: chatdb
    ports:
      - 27017:27017
    restart: always
    networks:
      - chat-network
networks:
  chat-network: 
    driver: bridge